### ISSUE TITLE
Use category field on GLPs over domain to sort by STEM

### ISSUE THREAD

**Issue by juddus** [HandsFree/teacherui-frontend#136]
## Issue summary
Currently the domain is used for sorting by STEM, the category option should be used.

**Comment by juddus** [comment]
Implemented in frontend I believe.
STEM subjects are still using the 'Domain' field in the backend however, this needs to be switched to only search the category field in the GLP.

cc @felixangell

**Comment by felixangell** [comment]
will the domain field still exist or is category replacing it? one thing to note is that the searching will possibly be broken for a while until the category fields are populated since most of them are empty or 'not implemented'.

**Comment by juddus** [comment]
@felixangell Domain will still exist as a sort of 'sub-category'.

Broken searching is fine for now as eventually all GLPs will use category (hopefully).

**Comment by felixangell** [comment]
This was implemented a while back
